# Generated by Django 5.2.4 on 2026-01-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('SNB', models.TextField()),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
    ]
