# Generated by Django 5.2.4 on 2026-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0005_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
